### ISSUE TITLE
Source code package name

### ISSUE THREAD

**Issue by davsclaus** [camel-labs/camel-labs#9]
We should consider not using `org.apache` as the package name, but instead use something like `org.camellabs` instead.

**Comment by hekonsek** [comment]
I propose to use just `com.github.camellabs` as a base package and `com.github.camellabs.iot.component.raspberrypi` for RPi in particular. If we use `org.camellabs`, then we should really purchase that domain. We also use `com.github.camellabs` as a groupId, because Sonatype won't allow us to deploy under `org.camellabs` until we purchase that domain.

**Comment by davsclaus** [comment]
Ah didnt know about the sonartype restriction, but sound very right in doing so.

Yeah lets go with the naming `com.github.camellabs`

**Comment by davsclaus** [comment]
Great looks good
